"""M1 durable catalog ingestion and query facts"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cw1_knowledge_bases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "key"),
    )
    op.create_index(
        op.f("ix_cw1_knowledge_bases_workspace_id"), "cw1_knowledge_bases", ["workspace_id"], unique=False
    )
    op.create_table(
        "cw1_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kb_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("active_version_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["kb_id"],
            ["cw1_knowledge_bases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cw1_documents_kb_id"), "cw1_documents", ["kb_id"], unique=False)
    op.create_table(
        "cw1_query_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("kb_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("candidates", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reserved_yuan", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("estimated_yuan", sa.Numeric(precision=12, scale=8), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["kb_id"],
            ["cw1_knowledge_bases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "key"),
    )
    op.create_index(op.f("ix_cw1_query_runs_workspace_id"), "cw1_query_runs", ["workspace_id"], unique=False)
    op.create_table(
        "cw1_document_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("kb_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=200), nullable=False),
        sa.Column("license", sa.String(length=40), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("blob_key", sa.String(length=64), nullable=False),
        sa.Column("canonical_key", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("index_collection", sa.String(length=120), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("profile", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("bm25", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["cw1_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["kb_id"],
            ["cw1_knowledge_bases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "sequence"),
        sa.UniqueConstraint("kb_id", "key"),
    )
    op.create_index(
        op.f("ix_cw1_document_versions_document_id"), "cw1_document_versions", ["document_id"], unique=False
    )
    op.create_index(op.f("ix_cw1_document_versions_kb_id"), "cw1_document_versions", ["kb_id"], unique=False)
    op.create_table(
        "cw1_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("block", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["cw1_document_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cw1_chunks_version_id"), "cw1_chunks", ["version_id"], unique=False)
    op.create_table(
        "cw1_ingestion_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_version_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("fence", sa.Integer(), nullable=False),
        sa.Column("owner", sa.String(length=80), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "available_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("pipeline_version", sa.String(length=100), nullable=False),
        sa.Column("events", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["cw1_document_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_version_id"),
    )
    op.create_index(op.f("ix_cw1_ingestion_jobs_status"), "cw1_ingestion_jobs", ["status"], unique=False)
    op.create_table(
        "cw1_citations",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["cw1_chunks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["cw1_query_runs.id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "evidence_id"),
    )
    op.create_table(
        "cw1_outbox",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["cw1_ingestion_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("job_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cw1_outbox")
    op.drop_table("cw1_citations")
    op.drop_index(op.f("ix_cw1_ingestion_jobs_status"), table_name="cw1_ingestion_jobs")
    op.drop_table("cw1_ingestion_jobs")
    op.drop_index(op.f("ix_cw1_chunks_version_id"), table_name="cw1_chunks")
    op.drop_table("cw1_chunks")
    op.drop_index(op.f("ix_cw1_document_versions_kb_id"), table_name="cw1_document_versions")
    op.drop_index(op.f("ix_cw1_document_versions_document_id"), table_name="cw1_document_versions")
    op.drop_table("cw1_document_versions")
    op.drop_index(op.f("ix_cw1_query_runs_workspace_id"), table_name="cw1_query_runs")
    op.drop_table("cw1_query_runs")
    op.drop_index(op.f("ix_cw1_documents_kb_id"), table_name="cw1_documents")
    op.drop_table("cw1_documents")
    op.drop_index(op.f("ix_cw1_knowledge_bases_workspace_id"), table_name="cw1_knowledge_bases")
    op.drop_table("cw1_knowledge_bases")
    # ### end Alembic commands ###
