"""M2 production core facts"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cw2_circuits",
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "cw2_operations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("target", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "key"),
    )
    op.create_index(op.f("ix_cw2_operations_workspace_id"), "cw2_operations", ["workspace_id"], unique=False)
    op.create_table(
        "cw2_eval_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("kb_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("dataset_id", sa.String(length=80), nullable=False),
        sa.Column("dataset_hash", sa.String(length=64), nullable=False),
        sa.Column("split", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("runtime_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["kb_id"],
            ["cw1_knowledge_bases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "key"),
    )
    op.create_index(op.f("ix_cw2_eval_runs_status"), "cw2_eval_runs", ["status"], unique=False)
    op.create_index(op.f("ix_cw2_eval_runs_workspace_id"), "cw2_eval_runs", ["workspace_id"], unique=False)
    op.create_table(
        "cw2_eval_cases",
        sa.Column("eval_run_id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("query_run_id", sa.Uuid(), nullable=True),
        sa.Column("owner", sa.Uuid(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("judge", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("human_review", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("judge_reserved_yuan", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("judge_estimated_yuan", sa.Numeric(precision=12, scale=8), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["eval_run_id"],
            ["cw2_eval_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["query_run_id"],
            ["cw1_query_runs.id"],
        ),
        sa.PrimaryKeyConstraint("eval_run_id", "case_id"),
    )
    op.create_index(op.f("ix_cw2_eval_cases_status"), "cw2_eval_cases", ["status"], unique=False)
    op.create_table(
        "cw2_indexes",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("fence", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["cw1_ingestion_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["cw1_document_versions.id"],
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index(op.f("ix_cw2_indexes_version_id"), "cw2_indexes", ["version_id"], unique=False)
    op.create_index(op.f("ix_cw2_indexes_workspace_id"), "cw2_indexes", ["workspace_id"], unique=False)
    op.add_column(
        "cw1_ingestion_jobs", sa.Column("kind", sa.String(length=24), server_default="ingest", nullable=False)
    )
    op.drop_constraint(
        op.f("cw1_ingestion_jobs_document_version_id_key"), "cw1_ingestion_jobs", type_="unique"
    )
    op.create_index(
        op.f("ix_cw1_ingestion_jobs_document_version_id"),
        "cw1_ingestion_jobs",
        ["document_version_id"],
        unique=False,
    )
    op.add_column(
        "cw1_query_runs",
        sa.Column(
            "index_bindings", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
    )
    op.add_column(
        "cw1_query_runs",
        sa.Column(
            "runtime_config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
    )
    op.add_column(
        "cw1_query_runs",
        sa.Column("stages", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
    )
    op.add_column(
        "cw1_query_runs",
        sa.Column("calls", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
    )
    op.add_column("cw1_query_runs", sa.Column("error_category", sa.String(length=24), nullable=True))
    op.add_column("cw1_query_runs", sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cw1_query_runs", "completed_at")
    op.drop_column("cw1_query_runs", "error_category")
    op.drop_column("cw1_query_runs", "calls")
    op.drop_column("cw1_query_runs", "stages")
    op.drop_column("cw1_query_runs", "runtime_config")
    op.drop_column("cw1_query_runs", "index_bindings")
    op.drop_index(op.f("ix_cw1_ingestion_jobs_document_version_id"), table_name="cw1_ingestion_jobs")
    op.create_unique_constraint(
        op.f("cw1_ingestion_jobs_document_version_id_key"),
        "cw1_ingestion_jobs",
        ["document_version_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("cw1_ingestion_jobs", "kind")
    op.drop_index(op.f("ix_cw2_indexes_workspace_id"), table_name="cw2_indexes")
    op.drop_index(op.f("ix_cw2_indexes_version_id"), table_name="cw2_indexes")
    op.drop_table("cw2_indexes")
    op.drop_index(op.f("ix_cw2_eval_cases_status"), table_name="cw2_eval_cases")
    op.drop_table("cw2_eval_cases")
    op.drop_index(op.f("ix_cw2_eval_runs_workspace_id"), table_name="cw2_eval_runs")
    op.drop_index(op.f("ix_cw2_eval_runs_status"), table_name="cw2_eval_runs")
    op.drop_table("cw2_eval_runs")
    op.drop_index(op.f("ix_cw2_operations_workspace_id"), table_name="cw2_operations")
    op.drop_table("cw2_operations")
    op.drop_table("cw2_circuits")
    # ### end Alembic commands ###
